apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: id-auth
  name: id-auth
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
  selector:
    k8s-app: id-auth