apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: id-editor
  name: id-editor
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8091
    targetPort: 8091
  selector:
    k8s-app: id-editor