---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: id-validation
  name: id-validation
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8293
    targetPort: 8293
  selector:
    k8s-app: id-validation

