---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: igapi
  name: igapi
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 18081
    targetPort: 18081
  selector:
    k8s-app: igapi

