---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: lrmservice
  name: lrmservice
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: lrmservice

