---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oso-task-int
  name: oso-task-int
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8787
    targetPort: 8787
  selector:
    k8s-app: oso-task-int

