---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oso-hcc-tile-update-int
  name: oso-hcc-tile-update-int
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 9999
  selector:
    k8s-app: oso-hcc-tile-update-int

