---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oso-export
  name: oso-export
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8101
    targetPort: 8101
  selector:
    k8s-app: oso-export

