apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: compiler-master-mc
  name: compiler-master-mc
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: compiler-master-mc
  template:
    metadata:
      labels:
        k8s-app: compiler-master-mc
      name: compiler-master-mc
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - compiler-master-mc
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: compiler-master-mc
      containers:
      - env:
        - name: RESULT_QUEUE_HOST
          value: 10.9.4.86
        - name: RESULT_QUEUE_CREATE_ON_START
          value: "True"
        - name: RESULT_QUEUE_PASSWORD
          value: idmq
        - name: START_QUEUE_USERNAME
          value: idmq
        - name: RESULT_QUEUE_ROUTING_KEY
          value: mc-result-queue
        - name: LISTENER_PORT
          value: "8888"
        - name: START_QUEUE_PASSWORD
          value: idmq
        - name: MASTER_ENDPOINT
          value: http://compiler-master-mc:8888
        - name: START_QUEUE_EXCHANGE
          value: amq.direct
        - name: START_QUEUE_PURGE_ON_START
          value: "False"
        - name: START_QUEUE_HOST
          value: 10.9.4.86
        - name: CONFIG_FILE
          value: /home/compiler-master/config_germany
        - name: RESULT_QUEUE_PORT
          value: "5672"
        - name: START_QUEUE_VHOST
          value: develope
        - name: START_QUEUE_ROUTING_KEY
          value: mc-start-queue
        - name: RESULT_QUEUE_USERNAME
          value: idmq
        - name: START_QUEUE_PORT
          value: "5672"
        - name: RESULT_QUEUE_VHOST
          value: develope
        - name: RESULT_QUEUE_PURGE_ON_START
          value: "False"
        - name: RESULT_QUEUE_QUEUE
          value: mc-result-queue
        - name: START_QUEUE_CREATE_ON_START
          value: "True"
        - name: PARTITION_RELATION
          value: "{'120000': [],'330400': [],'512000': [],'500000': [],'440300': [],'441900': [],'510600': [],'320500': [],'110000': [],'510100': [],'510900': [],'310000': [],'131000': [],'130700': [],'440100': [],'130800': [],'441300': [],'130200': [],'130300': [],'440600': [],'DE': [],'000000': [],'130100': [],'130400': [],'130500': [],'130600': [],'130900': [],'131100': [],'320100': [],'320200': [],'320300': [],'320400': [],'320600': [],'320700': [],'320800': [],'320900': [],'321000': [],'321100': [],'321200': [],'321300': [],'330100': [],'330200': [],'330300': [],'330500': [],'330600': [],'330700': [],'330800': [],'330900': [],'331000': [],'331100': [],'440200': [],'440400': [],'440500': [],'440700': [],'440800': [],'440900': [],'441200': [],'441400': [],'441500': [],'441600': [],'441700': [],'441800': [],'442000': [],'445100': [],'445200': [],'445300': [],'210100': [],'340100': [],'350100': [],'370100': [],'410100': [],'420100': [],'430100': [],'445300': [],'450100': [],'510100': [],'530100': [],'610100': []}"
        - name: RESULT_QUEUE_EXCHANGE
          value: amq.direct
        - name: WORKER_ENDPOINT
          value: http://compiler-worker:3333
        - name: START_QUEUE_QUEUE
          value: mc-start-queue
        #- name: LRM_SERVICE
        #  value: http://:8303/decodeolr?hst=1
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/compiler-master:20220706
        imagePullPolicy: Always
        name: compiler-master-mc
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 1000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

