apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: compiler-master-oem
  name: compiler-master-oem
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: compiler-master-oem
  #strategy:
  #  type: RollingUpdate
  #  rollingupdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  template:
    metadata:
      labels:
        k8s-app: compiler-master-oem
      name: compiler-master-oem
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - compiler-master-oem
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: compiler-master-oem
      containers:
      - env:
        - name: CONFIG_FILE
          value: /home/compiler-master/config_germany
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/compiler-master-oem:21q1sp1-v0-201125
        imagePullPolicy: Always
        name: compiler-master-oem
        ports:
        - containerPort: 6666
        resources:
          requests:
            cpu: 200m
            memory: 1000Mi
          limits:
            cpu: 200m
            memory: 1000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

