apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: compiler-master-ece
  name: compiler-master-ece
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: compiler-master-ece
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  #  type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: compiler-master-ece
      name: compiler-master-ece
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - compiler-master-ece
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: compiler-master-ece
      containers:
      - env:
        - name: CONFIG_FILE
          value: /home/compiler-master/config_germany
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/compiler-master-ece:20200327095536
        imagePullPolicy: Always
        name: compiler-master-ece
        ports:
        - containerPort: 4444
        resources:
          requests:
            cpu: 200m
            memory: 1000Mi
          limits:
            cpu: 200m
            memory: 1000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

