apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: hadauth
  name: hadauth
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hadauth
  template:
    metadata:
      labels:
        k8s-app: hadauth
      name: hadauth
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hadauth
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: hadauth
      containers:
      - name: hadauth
        #image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/hadauth:20220725T211135-eks-test
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/hadauth:20220617
        imagePullPolicy: Always
        ports:
        - containerPort: 8005
        resources:
          limits:
            cpu: 200m
            memory: 2000Mi
          requests:
            cpu: 200m
            memory: 2000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

