apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: id-auth
  name: id-auth
  namespace: hdms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: id-auth
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 30%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        k8s-app: id-auth
      name: id-auth
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - id-auth
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: id-auth
      containers:
      - env:
        - name: PROFILES
          value: ningxia-pro
        - name: CONSUL_IP
          value: http://10.9.4.86
        - name: CONSUL_PORT
          value: "8500"
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/id-auth:2022sp6-v0-220722
        imagePullPolicy: Always
        name: id-auth
        ports:
        - containerPort: 8200
        resources:
          limits:
            cpu: 1000m
            memory: 4000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

