apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: id-notification
  name: id-notification
  namespace: hdms-app
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: id-notification
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: id-notification
      name: id-notification
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - id-notification
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: id-notification
      containers:
      - env:
        - name: PROFILES
          value: ningxia-pro
        - name: CONSUL_IP
          value: http://10.9.4.86
        - name: CONSUL_PORT
          value: "8500"
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/id-notification:22q1sp2-v0-211213
        imagePullPolicy: Always
        name: id-notification
        ports:
        - containerPort: 8204
        resources:
          limits:
            cpu: 200m
            memory: 2000Mi
          requests:
            cpu: 200m
            memory: 2000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

