apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: id-upload
  name: id-upload
  namespace: hdms-app
spec:
  replicas: 8
  selector:
    matchLabels:
      k8s-app: id-upload
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: id-upload
      name: id-upload
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - id-upload
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: id-upload
      containers:
      - env:
        - name: PROFILES
          value: ningxia-pro
        - name: CONSUL_IP
          value: http://10.9.4.86
        - name: CONSUL_PORT
          value: "8500"
        - name: JAVA_OPTS
          value: -Xms16000m -Xmx16000m -XX:MetaspaceSize=512m -XX:+PrintFlagsFinal -Dspring.config.use-legacy-processing=true
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/id-upload:22sp6-v0-220719
        imagePullPolicy: Always
        name: id-upload
        ports:
        - containerPort: 8202
        resources:
          limits:
            cpu: 2000m
            memory: 16000Mi
          requests:
            cpu: 2000m
            memory: 16000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

