apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: igweb
  name: igweb
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: igweb
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 30%
  #    maxUnavailable: 75%
  #  type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: igweb
      name: igweb
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - igweb
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: igweb
      containers:
      - name: igweb
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/igweb:20Q1_V1_200107
        imagePullPolicy: Always
        ports:
        - containerPort: 8005
        resources:
          limits:
            cpu: 100m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

