apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: lrmservice
  name: lrmservice
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: lrmservice
  template:
    metadata:
      labels:
        k8s-app: lrmservice
      name: lrmservice
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - lrmservice
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: lrmservice
      containers:
      - name: lrmservice
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/lrmservice:v19.4.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 1000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

