apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nginx-lb
  name: nginx-lb
  namespace: hdms-app
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: nginx-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-lb
      name: nginx-lb
    spec:
      containers:
      - image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/nginx-lb:20211208
        imagePullPolicy: Always
        name: nginx-lb
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: nginx-log
          mountPath: /etc/nginx/hdms/log/
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      nodeSelector: 
        ingress-nginx-controller: hdms-pro
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-log
        hostPath:
          path: /data/nginx-log
          type: Directory
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
