apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oso-check
  name: oso-check
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oso-check
  #strategy:
  #  type: RollingUpdate
  #  rollingupdate:
  #    maxSurge: 30%
  #    maxUnavailable: 75%
  template:
    metadata:
      labels:
        k8s-app: oso-check
      name: oso-check
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - oso-check
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: oso-check
      containers:
      - env:
        - name: ENV_TAG
          value: k8s
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/oso-check:20220726
        imagePullPolicy: Always
        name: oso-check
        ports:
        - containerPort: 8003
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 500m
            memory: 1000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

