apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: ds-api
  name: ds-api
  namespace: dsg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ds-api
  template:
    metadata:
      labels:
        k8s-app: ds-api
      name: ds-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ds-api
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: ds-api
      containers:
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dsg/ds-api:1230_pro
        imagePullPolicy: IfNotPresent
        name: ds-api        
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 6
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30