apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: dsg-task
  name: dsg-task
  namespace: dsg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dsg-task
  template:
    metadata:
      labels:
        k8s-app: dsg-task
      name: dsg-task
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dsg-task
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: dsg-task
      containers:
      - image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dsg/dsg-task:22q3_sp1_V0_220419
        imagePullPolicy: IfNotPresent
        name: dsg-task
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30