apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: dsg-process
  name: dsg-process
  namespace: dsg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dsg-process
  template:
    metadata:
      labels:
        k8s-app: dsg-process
      name: dsg-process
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - dsg-process
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: dsg-process
      containers:
      - env:
        - name: PROFILES_ACTIVE
          value: ningxia-pro
        - name: CONSUL_HOST
          value: consul.dsg-infra.svc.cluster.local
        - name: CONSUL_PORT
          value: "8500"
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dsg/dsg-process:1230_pro
        imagePullPolicy: Always
        name: dsg-process
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8779
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8779
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 1536Mi
          requests:
            cpu: "1"
            memory: 1536Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30