apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: id-editor
  name: id-editor
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: id-editor
  template:
    metadata:
      labels:
        k8s-app: id-editor
      name: id-editor
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - id-editor
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: id-editor
      containers:
      - env:
        - name: PROFILES
          value: ningxia-pro
        - name: CONSUL_IP
          value: http://10.9.4.86
        - name: CONSUL_PORT
          value: "8500"
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/id-editor:v19.4.1
        imagePullPolicy: Always
        name: id-editor
        ports:
        - containerPort: 8091
        resources:
          limits:
            cpu: 100m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30