apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oso-hstdata-st2pg
  name: oso-hstdata-st2pg
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oso-hstdata-st2pg
  template:
    metadata:
      labels:
        k8s-app: oso-hstdata-st2pg
      name: oso-hstdata-st2pg
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - oso-hstdata-st2pg
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: oso-hstdata-st2pg
      containers:
      - env:
        - name: PROFILES
          value: ningxia-pro
        - name: CONSUL_IP
          value: http://10.9.4.86
        - name: CONSUL_PORT
          value: "8500"
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/oso-hstdata-st2pg:2022sp6-v0-220705
        imagePullPolicy: Always
        name: oso-hstdata-st2pg
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 2000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

