apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: webportal
  name: webportal
  namespace: hdms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: webportal
  template:
    metadata:
      labels:
        k8s-app: webportal
      name: webportal
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - webportal
            topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: webportal
      containers:
      - name: webportal
        image: 388144527693.dkr.ecr.cn-northwest-1.amazonaws.com.cn/hdms/webportal:20220725T211201-eks-test
        imagePullPolicy: Always
        ports:
        - containerPort: 8005
        resources:
          limits:
            cpu: 200m
            memory: 2000Mi
          requests:
            cpu: 200m
            memory: 2000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

