---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: compiler-master-oem
  name: compiler-master-oem
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 6666
    targetPort: 6666
  selector:
    k8s-app: compiler-master-oem

