---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: compiler-master-mc-sta
  name: compiler-master-mc-sta
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8899
    targetPort: 8899
  selector:
    k8s-app: compiler-master-mc-sta

