---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: compiler-master-oem-china-int
  name: compiler-master-oem-china-int
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 6665
    targetPort: 6665
  selector:
    k8s-app: compiler-master-oem-china-int

