---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: compiler-worker-oso
  name: compiler-worker-oso
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 3334
    targetPort: 3334
  selector:
    k8s-app: compiler-worker-oso

