---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: hadauth
  name: hadauth
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
  selector:
    k8s-app: hadauth

