---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: id-upload
  name: id-upload
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8202
    targetPort: 8202
  selector:
    k8s-app: id-upload

