---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: igweb
  name: igweb
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8005
    targetPort: 8005
  selector:
    k8s-app: igweb

