---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oemgui
  name: oemgui
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8004
  selector:
    k8s-app: oemgui

