---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: webportal
  name: webportal
  namespace: hdms-app
spec:
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  selector:
    k8s-app: webportal

